<?php

return [
    'templateWeekNum'=>0,
    'months'=>[
        0=>[
            'protein'=>190,
            'fat'=>90,
            'carbohydrates'=>230,
            'energy'=>2490,
        ]
    ],
    'weekdays'=>[
        0=>[
            'protein'=>1,
            'fat'=>1,
            'carbohydrates'=>1,
            'energy'=>1,
        ],
        5=>[
            'protein'=>1.2,
            'fat'=>1.4,
            'carbohydrates'=>1.8,
            'energy'=>1.48,
        ],
        6=>[
            'protein'=>1.1,
            'fat'=>1.2,
            'carbohydrates'=>1.3,
            'energy'=>1.2,
        ],
        1=>[
            'protein'=>1,
            'fat'=>0.9,
            'carbohydrates'=>0.85,
            'energy'=>0.92,
        ],
        2=>[
            'protein'=>1.05,
            'fat'=>0.8,
            'carbohydrates'=>0.8,
            'energy'=>0.89,
        ],
        3=>[
            'protein'=>1,
            'fat'=>0.75,
            'carbohydrates'=>0.7,
            'energy'=>0.82,
        ],
        4=>[
            'protein'=>1,
            'fat'=>0.6,
            'carbohydrates'=>0.4,
            'energy'=>0.71,
        ],
    ],
];